spring.application.name=hotelbooking

spring.web.error.include-message=always

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/bookings
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA and Hibernate: transforming the classes into tables; create-drop recreates the db every run
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
# Tells Spring to run data.sql always after creating the tables
spring.sql.init.mode=always
#Delays the data.sql sqript to run until Hibernate finishes creating the tables
spring.jpa.defer-datasource-initialization=true