spring.application.name=hotelbooking

spring.web.error.include-message=always

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/rooms
spring.datasource.username=postgres
spring.datasource.password=user

# JPA and Hibernate: transforming the classes into tables; create-drop recreates the db every run
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true